### ISSUE TITLE
Example of how things work in the README

### ISSUE THREAD

**Issue by EmilStenstrom** [xrudelis/pytrait#1]
Hi! I think this looks interesting (found on HN), but I'd like to see an example of how PyTraits is used. My suggestion would be to add it to the top of the README, to tell random people like me what this is.

**Comment by arekbal** [comment]
[Examples](https://github.com/xrudelis/pytrait/tree/master/examples) are in "strangely" called `./examples` directory. :) 
What I haven't undertood (the name-convention part and that it automatically works for all impls) I got from source code.

**Comment by xrudelis** [comment]
I added some concise snippets in the README and also some explanation on the Impl name convention part. It's also now optional to loosen the naming restricting by passing a `target` argument, so I think that should help with the most confusing part of this package.

**Comment by EmilStenstrom** [comment]
Thanks, makes things much clearer! :)
